services:
  authors_db:
    image: postgres
    container_name: authors_db
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: authors
      POSTGRES_PASSWORD: guest
      POSTGRES_USER: guest
      PG_TRUST_LOCALNET: 'true'
  books_db:
    image: postgres
    container_name: books_db
    ports:
      - "5433:5432"
    environment:
      POSTGRES_DB: books
      POSTGRES_PASSWORD: guest
      POSTGRES_USER: guest
      PG_TRUST_LOCALNET: 'true'
